import { useEffect, useMemo, useState } from "react";
import type { Job, NavKey } from "../../core/types";
import { Icon, type IconName } from "../../shared/Icon";
import { Pagination } from "../../shared/Pagination";

type WorkflowKey = "sources" | "story" | "timeline" | "brand";
type WorkflowPageProps = { kind: WorkflowKey; jobs: Job[]; onNavigate: (key: NavKey) => void };

const CONFIG: Record<WorkflowKey, { kicker: string; title: string; description: string; icon: IconName; accent: string; next: NavKey; nextLabel: string; steps: Array<{ title: string; detail: string; action?: NavKey }> }> = {
  sources: { kicker: "WORKFLOW / 01", title: "Nguồn video", description: "Quản lý video gốc, URL, proxy và dữ liệu phân tích trước khi viết câu chuyện.", icon: "folder", accent: "#b9ea6c", next: "batch", nextLabel: "Mở trình tạo job", steps: [{ title: "Nạp video gốc", detail: "File local hoặc URL sẽ được tải vào cache, probe duration/FPS/audio và giữ nguyên bản gốc." }, { title: "Tạo proxy & thumbnails", detail: "Chuẩn hoá preview nhẹ để duyệt nhanh mà không thay đổi source asset." }, { title: "Sẵn sàng phân tích", detail: "Asset có checksum và metadata để retry không tải lại video.", action: "analysis" }] },
  story: { kicker: "WORKFLOW / 03", title: "Kịch bản & Voice", description: "Biến ý chính thành lời kể đúng ngách, duyệt text rồi tạo audio theo từng đoạn.", icon: "mic", accent: "#d5ed8f", next: "timeline", nextLabel: "Mở chọn cảnh & timeline", steps: [{ title: "Chọn phong cách kể", detail: "Ngách, khán giả, tone, hook và thời lượng là context chung của kịch bản." }, { title: "Duyệt voice script", detail: "Mỗi đoạn script gắn với scene nguồn; có thể sửa, khoá câu và regenerate từng đoạn." }, { title: "Tạo voice theo segment", detail: "Audio có timing và waveform để kéo thả, nghe thử hoặc retry.", action: "timeline" }] },
  timeline: { kicker: "WORKFLOW / 05", title: "Chọn cảnh & Timeline", description: "AI nhặt cảnh từ chính video gốc để từng câu voice khớp hành động và hình ảnh.", icon: "video", accent: "#72d9d0", next: "brand", nextLabel: "Mở phụ đề & thương hiệu", steps: [{ title: "Voice → source scene", detail: "Mỗi voice segment có source_start/end, match score, lý do chọn và cảnh dự phòng." }, { title: "Duyệt sync", detail: "Xem song song original/reframe; cảnh thiếu bằng chứng sẽ được đánh dấu cần duyệt." }, { title: "Dựng track", detail: "Video, voice, audio gốc, nhạc, phụ đề và logo nằm trên timeline riêng.", action: "brand" }] },
  brand: { kicker: "WORKFLOW / 07", title: "Phụ đề & Thương hiệu", description: "Hoàn thiện bản xuất với phụ đề đồng bộ voice, logo và safe-area theo nền tảng.", icon: "captions", accent: "#a6b6ff", next: "render", nextLabel: "Mở render & xuất bản", steps: [{ title: "Subtitle timing", detail: "Tạo phụ đề từ audio đã duyệt, hỗ trợ song ngữ và highlight từ khoá." }, { title: "Logo / watermark", detail: "Chọn file, vị trí, opacity, kích thước và margin an toàn trên track riêng." }, { title: "Preview trước render", detail: "Kiểm tra không tràn safe-area, không clipping audio và đúng tỷ lệ output.", action: "render" }] },
};

export function WorkflowPage({ kind, jobs, onNavigate }: WorkflowPageProps) {
  const config = CONFIG[kind];
  const [page, setPage] = useState(1);
  const [pageSize, setPageSize] = useState(5);
  const pageJobs = useMemo(() => jobs.slice((page - 1) * pageSize, page * pageSize), [jobs, page, pageSize]);
  useEffect(() => {
    setPage((current) => Math.min(current, Math.max(1, Math.ceil(jobs.length / pageSize))));
  }, [jobs.length, pageSize]);
  return <div className={`page-stack page-enter workflow-page workflow-${kind}`}>
    <div className="page-title"><div><p className="eyebrow">{config.kicker}</p><h2>{config.title}</h2><p>{config.description}</p></div><div className="tw-flex tw-flex-wrap tw-items-center tw-justify-end tw-gap-2"><span className="workflow-module-icon tw-inline-flex tw-items-center tw-gap-2 tw-rounded-full tw-border tw-border-white/10 tw-bg-white/5 tw-px-3 tw-py-2 tw-text-[10px] tw-text-slate-300" style={{ color: config.accent }}><Icon name={config.icon} size={14} /> Module độc lập</span><button type="button" className="button-quiet" onClick={() => onNavigate(config.next)}><Icon name="arrow" size={14} /> {config.nextLabel}</button></div></div>
    <section className="tw-grid tw-gap-4 lg:tw-grid-cols-[1.15fr_.85fr]">
      <div className="panel-card tw-overflow-hidden tw-p-5 sm:tw-p-7"><div className="tw-flex tw-items-start tw-justify-between tw-gap-4"><div><p className="eyebrow">PIPELINE MAP</p><h3 className="!tw-mt-2">Luồng xử lý trong module</h3></div><span className="tw-grid tw-h-10 tw-w-10 tw-place-items-center tw-rounded-xl tw-border tw-border-lime/20 tw-bg-lime/10 tw-text-lime"><Icon name={config.icon} size={20} /></span></div><div className="tw-mt-6 tw-grid tw-gap-3">{config.steps.map((step, index) => <div key={step.title} className="tw-flex tw-items-start tw-gap-3 tw-rounded-xl tw-border tw-border-white/10 tw-bg-black/10 tw-p-3"><span className="tw-grid tw-h-7 tw-w-7 tw-shrink-0 tw-place-items-center tw-rounded-lg tw-bg-white/10 tw-font-mono tw-text-xs" style={{ color: config.accent }}>{String(index + 1).padStart(2, "0")}</span><div className="tw-min-w-0 tw-flex-1"><strong className="tw-block tw-text-sm tw-text-slate-100">{step.title}</strong><p className="tw-mt-1 tw-text-xs tw-leading-5 tw-text-slate-400">{step.detail}</p></div>{step.action && <button className="button-quiet tw-shrink-0" title="Mở bước tiếp theo" aria-label="Mở bước tiếp theo" onClick={() => onNavigate(step.action!)}><Icon name="arrow" size={13} /></button>}</div>)}</div></div>
      <div className="panel-card tw-p-5 sm:tw-p-7"><p className="eyebrow">QUALITY CHECKS</p><h3 className="!tw-mt-2">Điểm cần duyệt</h3><div className="tw-mt-5 tw-grid tw-gap-2">{["Bám đúng nội dung video gốc", "Voice và cảnh cùng mốc thời gian", "Không thêm dữ kiện ngoài source", "Subtitle/logo nằm trong safe-area"].map((item) => <div key={item} className="tw-flex tw-items-center tw-gap-2 tw-rounded-lg tw-bg-white/5 tw-p-3 tw-text-xs tw-text-slate-300"><Icon name="check" size={14} /> {item}</div>)}</div><button className="button-quiet tw-mt-5 tw-w-full" onClick={() => onNavigate(kind === "sources" ? "analysis" : kind === "story" ? "timeline" : kind === "timeline" ? "brand" : "render")}><Icon name="arrow" size={14} /> Tiếp tục workflow</button></div>
    </section>
    <section className="panel-card tw-p-5 sm:tw-p-7"><div className="tw-flex tw-flex-wrap tw-items-end tw-justify-between tw-gap-3"><div><p className="eyebrow">RECENT RECORDS</p><h3 className="!tw-mt-2">Job liên quan</h3></div><label className="tw-flex tw-items-center tw-gap-2 tw-text-[10px] tw-text-slate-400">Hiển thị <select className="!tw-w-auto !tw-py-1" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}><option value={5}>5</option><option value={10}>10</option><option value={25}>25</option><option value={50}>50</option></select> dòng</label></div><div className="tw-mt-4 tw-overflow-x-auto"><table className="tw-w-full tw-min-w-[560px] tw-text-left tw-text-xs"><thead className="tw-border-b tw-border-white/10 tw-text-[10px] tw-uppercase tw-tracking-[.16em] tw-text-slate-500"><tr><th className="tw-p-3">Tên job</th><th className="tw-p-3">Nguồn</th><th className="tw-p-3">Trạng thái</th><th className="tw-p-3">Tiến độ</th></tr></thead><tbody>{pageJobs.map((job) => <tr key={job.id} className="tw-border-b tw-border-white/5"><td className="tw-p-3 tw-font-semibold tw-text-slate-200">{job.name}</td><td className="tw-max-w-[220px] tw-truncate tw-p-3 tw-font-mono tw-text-[10px] tw-text-slate-500">{job.source}</td><td className="tw-p-3 tw-text-slate-400">{job.status}</td><td className="tw-p-3"><div className="tw-flex tw-items-center tw-gap-2"><div className="tw-h-1.5 tw-flex-1 tw-rounded-full tw-bg-white/10"><i className="tw-block tw-h-full tw-rounded-full tw-bg-lime" style={{ width: `${job.progress}%` }} /></div><span className="tw-w-8 tw-text-right tw-font-mono tw-text-[10px] tw-text-slate-400">{job.progress}%</span></div></td></tr>)}</tbody></table>{!pageJobs.length && <p className="tw-py-8 tw-text-center tw-text-xs tw-text-slate-500">Chưa có dữ liệu trong module này.</p>}</div><div className="tw-mt-4"><Pagination total={jobs.length} page={page} pageSize={pageSize} onPageChange={setPage} /></div></section>
  </div>;
}
