const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const childProcess = require("node:child_process");

// The raw platform identifier never leaves the device. This salt keeps the
// JACS identifier separate from identifiers generated by other applications.
const APP_SALT = "jacs-studio-hwid-v1";

function normalizeIdentifier(value) {
  // `reg.exe` can return UTF-16 data with embedded NULs when launched from
  // Electron; remove them before parsing the identifier.
  return String(value ?? "").replace(/\0/g, "").trim().replace(/^"|"$/g, "");
}

function readMacPlatformUuid(execFileSync = childProcess.execFileSync) {
  try {
    const output = execFileSync("/usr/sbin/ioreg", ["-rd1", "-c", "IOPlatformExpertDevice"], { encoding: "utf8" });
    return normalizeIdentifier(output.match(/"IOPlatformUUID"\s*=\s*"([^"]+)"/i)?.[1]);
  } catch {
    return "";
  }
}

function readWindowsMachineGuid(execFileSync = childProcess.execFileSync) {
  try {
    const output = execFileSync("reg.exe", ["query", "HKLM\\SOFTWARE\\Microsoft\\Cryptography", "/v", "MachineGuid"], { encoding: "utf8", windowsHide: true });
    const line = output.split(/\r?\n/).map(normalizeIdentifier).find((item) => /MachineGuid\s+REG_/i.test(item));
    return normalizeIdentifier(line?.match(/MachineGuid\s+REG_\S+\s+(.+)$/i)?.[1]);
  } catch {
    return "";
  }
}

function readLinuxMachineId(fsImpl = fs) {
  for (const filePath of ["/etc/machine-id", "/var/lib/dbus/machine-id"]) {
    try {
      const value = normalizeIdentifier(fsImpl.readFileSync(filePath, "utf8"));
      if (value) return value;
    } catch {
      // Try the next well-known location.
    }
  }
  return "";
}

function readPlatformIdentifier(platform, dependencies = {}) {
  const execFileSync = dependencies.execFileSync ?? childProcess.execFileSync;
  const fsImpl = dependencies.fsImpl ?? fs;
  if (platform === "darwin") return readMacPlatformUuid(execFileSync);
  if (platform === "win32") return readWindowsMachineGuid(execFileSync);
  if (platform === "linux") return readLinuxMachineId(fsImpl);
  return "";
}

function readOrCreateInstallationId(userDataPath, fsImpl = fs, randomUUID = crypto.randomUUID) {
  const filePath = path.join(userDataPath, "installation-id");
  try {
    const existing = normalizeIdentifier(fsImpl.readFileSync(filePath, "utf8"));
    if (existing) return existing;
  } catch {
    // Generate an identifier below when this is the first launch.
  }
  const generated = randomUUID();
  fsImpl.mkdirSync(userDataPath, { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  fsImpl.writeFileSync(temporaryPath, generated, { encoding: "utf8", mode: 0o600 });
  fsImpl.renameSync(temporaryPath, filePath);
  return generated;
}

function createMachineInfo({ platform = process.platform, arch = process.arch, appVersion = "0.0.0", userDataPath, dependencies = {} }) {
  const platformIdentifier = readPlatformIdentifier(platform, dependencies);
  const source = platformIdentifier ? "platform" : "installation";
  const rawIdentifier = platformIdentifier || readOrCreateInstallationId(userDataPath, dependencies.fsImpl ?? fs, dependencies.randomUUID ?? crypto.randomUUID);
  const platformName = platform === "darwin" ? "macos" : platform === "win32" ? "windows" : "linux";
  const digest = crypto.createHash("sha256").update(`${APP_SALT}:${platformName}:${rawIdentifier}`).digest("hex").slice(0, 32).toUpperCase();
  const prefix = platformName === "macos" ? "MAC" : platformName === "windows" ? "WIN" : "LNX";
  return { machineId: `JACS-${prefix}-${digest}`, machineIdSource: source, platform: platformName, arch, appVersion };
}

module.exports = {
  APP_SALT,
  createMachineInfo,
  normalizeIdentifier,
  readLinuxMachineId,
  readMacPlatformUuid,
  readOrCreateInstallationId,
  readPlatformIdentifier,
  readWindowsMachineGuid,
};
