const crypto = require("node:crypto");
const fs = require("node:fs");
const path = require("node:path");
const childProcess = require("node:child_process");
const os = require("node:os");

// The raw platform identifier never leaves the device. This salt keeps the
// JACS identifier separate from identifiers generated by other applications.
const APP_SALT = "jacs-studio-hwid-v2-hardened-meridians";

function normalizeIdentifier(value) {
  return String(value ?? "")
    .replace(/\0/g, "")
    .trim()
    .replace(/^"|"$/g, "");
}

function readMacPlatformUuid(execFileSync = childProcess.execFileSync) {
  try {
    const output = execFileSync("/usr/sbin/ioreg", ["-rd1", "-c", "IOPlatformExpertDevice"], {
      encoding: "utf8",
    });
    const uuid = output.match(/"IOPlatformUUID"\s*=\s*"([^"]+)"/i)?.[1];
    const serial = output.match(/"IOPlatformSerialNumber"\s*=\s*"([^"]+)"/i)?.[1];
    return normalizeIdentifier(`${uuid || ""}_${serial || ""}`);
  } catch {
    return "";
  }
}

function readWindowsMachineGuid(execFileSync = childProcess.execFileSync) {
  try {
    // 1. Primary: Windows Cryptography MachineGuid
    const guidOutput = execFileSync(
      "reg.exe",
      ["query", "HKLM\\SOFTWARE\\Microsoft\\Cryptography", "/v", "MachineGuid"],
      { encoding: "utf8", windowsHide: true }
    );
    const line = guidOutput
      .split(/\r?\n/)
      .map(normalizeIdentifier)
      .find((item) => /MachineGuid\s+REG_/i.test(item));
    const guid = normalizeIdentifier(line?.match(/MachineGuid\s+REG_\S+\s+(.+)$/i)?.[1]) || "";

    // 2. Secondary hardware component IDs: BIOS & BaseBoard Serial
    let boardSerial = "";
    try {
      const boardOutput = execFileSync("wmic", ["baseboard", "get", "serialnumber"], {
        encoding: "utf8",
        windowsHide: true,
        timeout: 1200,
      });
      boardSerial =
        boardOutput
          .split(/\r?\n/)
          .map((l) => l.trim())
          .filter((l) => l && !/serialnumber/i.test(l))[0] || "";
    } catch {}

    let cpuId = "";
    try {
      const cpuOutput = execFileSync("wmic", ["cpu", "get", "processorid"], {
        encoding: "utf8",
        windowsHide: true,
        timeout: 1200,
      });
      cpuId =
        cpuOutput
          .split(/\r?\n/)
          .map((l) => l.trim())
          .filter((l) => l && !/processorid/i.test(l))[0] || "";
    } catch {}

    return normalizeIdentifier(`${guid}:${boardSerial}:${cpuId}`);
  } catch {
    return "";
  }
}

function readLinuxMachineId(fsImpl = fs) {
  for (const filePath of ["/etc/machine-id", "/var/lib/dbus/machine-id", "/sys/class/dmi/id/product_uuid"]) {
    try {
      const value = normalizeIdentifier(fsImpl.readFileSync(filePath, "utf8"));
      if (value) return value;
    } catch {
      // Try the next well-known location.
    }
  }
  return "";
}

function readPlatformIdentifier(platform, dependencies = {}) {
  const execFileSync = dependencies.execFileSync ?? childProcess.execFileSync;
  const fsImpl = dependencies.fsImpl ?? fs;
  if (platform === "darwin") return readMacPlatformUuid(execFileSync);
  if (platform === "win32") return readWindowsMachineGuid(execFileSync);
  if (platform === "linux") return readLinuxMachineId(fsImpl);
  return "";
}

function readOrCreateInstallationId(userDataPath, fsImpl = fs, randomUUID = crypto.randomUUID) {
  const filePath = path.join(userDataPath, "installation-id");
  try {
    const existing = normalizeIdentifier(fsImpl.readFileSync(filePath, "utf8"));
    if (existing) return existing;
  } catch {
    // Generate an identifier below when this is the first launch.
  }
  const generated = randomUUID();
  fsImpl.mkdirSync(userDataPath, { recursive: true });
  const temporaryPath = `${filePath}.tmp-${process.pid}`;
  fsImpl.writeFileSync(temporaryPath, generated, { encoding: "utf8", mode: 0o600 });
  fsImpl.renameSync(temporaryPath, filePath);
  return generated;
}

function collectClientHardwareInfo() {
  const cpus = os.cpus() || [];
  const cpuModel = cpus[0]?.model ? cpus[0].model.trim() : "Multi-Core CPU";
  const cpuCores = cpus.length || 4;
  const totalMemoryGb = Number((os.totalmem() / (1024 * 1024 * 1024)).toFixed(1));
  const freeMemoryGb = Number((os.freemem() / (1024 * 1024 * 1024)).toFixed(1));

  let gpuName = "Standard GPU Acceleration";
  let gpuVramGb = 4.0;
  let gpuUsedVramGb = 1.2;
  let gpuTemperature = 32;
  let gpuUtilization = 15;
  let encoder = "cpu";
  let hasNvidia = false;
  let hasIntel = false;
  let hasAmd = false;
  let hasApple = process.platform === "darwin";

  // 1. Try nvidia-smi for dedicated NVIDIA cards
  try {
    const nvsmi = childProcess.execSync(
      "nvidia-smi --query-gpu=name,memory.total,memory.used,temperature.gpu,utilization.gpu --format=csv,noheader,nounits",
      { encoding: "utf8", windowsHide: true, timeout: 1500 }
    );
    const parts = nvsmi.trim().split(",");
    if (parts.length >= 5) {
      gpuName = parts[0].trim();
      const totalMb = parseFloat(parts[1]) || 4096;
      const usedMb = parseFloat(parts[2]) || 1024;
      gpuVramGb = Number((totalMb / 1024).toFixed(1));
      gpuUsedVramGb = Number((usedMb / 1024).toFixed(1));
      gpuTemperature = parseInt(parts[3], 10) || 35;
      gpuUtilization = parseInt(parts[4], 10) || 10;
      encoder = "nvenc";
      hasNvidia = true;
    }
  } catch {}

  // 2. Windows WMIC / VideoController detection for Intel / AMD / NVIDIA
  if (!hasNvidia && process.platform === "win32") {
    try {
      const output = childProcess.execSync("wmic path win32_VideoController get Name,AdapterRAM", {
        encoding: "utf8",
        windowsHide: true,
        timeout: 2500,
      });
      const lines = output.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
      for (const line of lines.slice(1)) {
        const match = line.match(/^(\d+)\s+(.+)$/);
        if (match) {
          const bytes = parseInt(match[1], 10) || 0;
          const name = match[2].trim();
          if (name && !name.toLowerCase().includes("virtual") && !name.toLowerCase().includes("remote")) {
            gpuName = name;
            const gb = bytes / (1024 * 1024 * 1024);
            gpuVramGb = gb > 0.5 ? Number(gb.toFixed(1)) : (totalMemoryGb >= 16 ? 4.0 : 2.0);
            if (/nvidia/i.test(name)) {
              encoder = "nvenc";
              hasNvidia = true;
            } else if (/intel/i.test(name)) {
              encoder = "qsv";
              hasIntel = true;
            } else if (/amd|radeon/i.test(name)) {
              encoder = "amf";
              hasAmd = true;
            }
            break;
          }
        }
      }
    } catch {}
  }

  // 3. macOS Apple Silicon GPU detection
  if (process.platform === "darwin") {
    encoder = "videotoolbox";
    hasApple = true;
    try {
      const macGpu = childProcess.execSync("system_profiler SPDisplaysDataType", {
        encoding: "utf8",
        timeout: 2500,
      });
      const match = macGpu.match(/Chipset Model:\s*(.+)/i);
      if (match?.[1]) gpuName = match[1].trim();
      gpuVramGb = totalMemoryGb >= 16 ? 8.0 : 4.0;
    } catch {
      gpuName = "Apple Silicon GPU";
    }
  }

  return {
    cpuModel,
    cpuCores,
    totalMemoryGb,
    freeMemoryGb,
    gpuName,
    gpuVramGb,
    gpuUsedVramGb,
    gpuTemperature,
    gpuUtilization,
    encoder,
    hasNvidia,
    hasIntel,
    hasAmd,
    hasApple,
  };
}

function createMachineInfo({
  platform = process.platform,
  arch = process.arch,
  appVersion = "0.0.0",
  userDataPath,
  dependencies = {},
}) {
  const platformIdentifier = readPlatformIdentifier(platform, dependencies);
  const source = platformIdentifier ? "platform" : "installation";
  const rawIdentifier =
    platformIdentifier ||
    readOrCreateInstallationId(
      userDataPath,
      dependencies.fsImpl ?? fs,
      dependencies.randomUUID ?? crypto.randomUUID
    );
  const platformName = platform === "darwin" ? "macos" : platform === "win32" ? "windows" : "linux";
  const digest = crypto
    .createHash("sha256")
    .update(`${APP_SALT}:${platformName}:${rawIdentifier}`)
    .digest("hex")
    .slice(0, 32)
    .toUpperCase();
  const prefix = platformName === "macos" ? "MAC" : platformName === "windows" ? "WIN" : "LNX";

  const hw = collectClientHardwareInfo();

  return {
    machineId: `JACS-${prefix}-${digest}`,
    machineIdSource: source,
    platform: platformName,
    arch,
    appVersion,
    cpuModel: hw.cpuModel,
    cpuCores: hw.cpuCores,
    totalMemoryGb: hw.totalMemoryGb,
    freeMemoryGb: hw.freeMemoryGb,
    gpuName: hw.gpuName,
    gpuVramGb: hw.gpuVramGb,
    gpuUsedVramGb: hw.gpuUsedVramGb,
    gpuTemperature: hw.gpuTemperature,
    gpuUtilization: hw.gpuUtilization,
    encoder: hw.encoder,
    hasNvidia: hw.hasNvidia,
    hasIntel: hw.hasIntel,
    hasAmd: hw.hasAmd,
    hasApple: hw.hasApple,
  };
}

module.exports = {
  APP_SALT,
  collectClientHardwareInfo,
  createMachineInfo,
  normalizeIdentifier,
  readLinuxMachineId,
  readMacPlatformUuid,
  readOrCreateInstallationId,
  readPlatformIdentifier,
  readWindowsMachineGuid,
};
