export const VIETNAMESE_BANKS = [
  { bin: "970422", name: "MB Bank (Ngân hàng Quân Đội)", short: "MB" },
  { bin: "970436", name: "Vietcombank (Ngoại thương Việt Nam)", short: "VCB" },
  { bin: "970407", name: "Techcombank (Kỹ thương Việt Nam)", short: "TCB" },
  { bin: "970416", name: "ACB (Ngân hàng Á Châu)", short: "ACB" },
  { bin: "970432", name: "VPBank (Việt Nam Thịnh Vượng)", short: "VPB" },
  { bin: "970423", name: "TPBank (Tiên Phong)", short: "TPB" },
  { bin: "970418", name: "BIDV (Đầu tư và Phát triển)", short: "BIDV" },
  { bin: "970415", name: "VietinBank (Công thương Việt Nam)", short: "CTG" },
  { bin: "970403", name: "Sacombank (Sài Gòn Thương Tín)", short: "STB" },
  { bin: "970437", name: "HDBank (Phát triển TP.HCM)", short: "HDB" },
  { bin: "970448", name: "OCB (Phương Đông)", short: "OCB" },
  { bin: "970441", name: "VIB (Quốc tế)", short: "VIB" },
  { bin: "970443", name: "SHB (Sài Gòn - Hà Nội)", short: "SHB" },
  { bin: "970440", name: "SeABank (Đông Nam Á)", short: "SEAB" },
  { bin: "970426", name: "MSB (Hàng Hải)", short: "MSB" },
  { bin: "970449", name: "LPBank (Lộc Phát Việt Nam)", short: "LPB" },
  { bin: "970405", name: "Agribank (Nông nghiệp & PTNT)", short: "VBA" },
];
