import { useEffect, useState } from "react";
import type { FormEvent } from "react";
import { ApiRequestError, getApiBaseUrl, validateLicense } from "../../core/api";
import { getRuntime } from "../../core/runtime";
import type { MachineInfo } from "../../core/types";
import { Icon } from "../../shared/Icon";

export function ActivationPage({ onActivated }: { onActivated?: (value: boolean) => void }) {
  const [machine, setMachine] = useState<MachineInfo | null>(null); const [key, setKey] = useState(""); const [saved, setSaved] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => {
    void getRuntime().getMachineInfo().then(setMachine);
    void getRuntime().readLicense().then((value) => {
      if (!value) return;
      setKey(value);
      setSaved(true);
    });
  }, []);
  async function activate(event: FormEvent) { event.preventDefault(); setMessage(""); if (!machine || !key.trim()) return; const normalizedKey = key.replace(/[\s\u200b-\u200d\ufeff]+/g, "").toUpperCase(); try { await validateLicense(normalizedKey, machine.machineId); await getRuntime().saveLicense(normalizedKey); setKey(normalizedKey); setSaved(true); setMessage("Kích hoạt thành công trên thiết bị này."); onActivated?.(true); } catch (error) { if (error instanceof ApiRequestError) { const hint = error.code === "LICENSE_HWID_MISMATCH" ? "Key này đang gán cho mã máy khác." : error.code === "LICENSE_EXPIRED" ? "Key đã hết hạn. Vui lòng liên hệ Admin để gia hạn." : error.code === "LICENSE_HWID_INVALID" ? "Mã máy không hợp lệ. Hãy dùng bản Electron đã cài đặt." : error.code === "LICENSE_INVALID" ? "Key sai, chưa được cấp ở môi trường này hoặc đã bị khóa." : error.message; setMessage(`${hint} (${getApiBaseUrl()})`); } else setMessage(error instanceof Error ? error.message : "Kích hoạt thất bại"); } }
  async function clear() { await getRuntime().clearLicense(); setSaved(false); setKey(""); setMessage("Đã xóa license cục bộ. Bạn có thể kích hoạt lại bằng key mới."); onActivated?.(false); }
  return <div className="page-stack page-enter"><div className="page-title"><div><p className="eyebrow">ACCOUNT / LICENSE</p><h2>License & thiết bị</h2><p>Key được cấp theo mã máy thật của thiết bị và chỉ lưu an toàn trên hệ điều hành.</p></div><span className={`connection-badge ${saved ? "connected" : ""}`}><i />{saved ? "Đã kích hoạt" : "Chưa kích hoạt"}</span></div><div className="activation-layout"><section className="panel-card device-card"><div className="device-art"><Icon name="key" size={29} /></div><p className="eyebrow">DEVICE ID</p><h3>{machine?.machineId ?? "Đang đọc mã máy..."}</h3><p className="subtle">Mã được tạo từ định danh hệ thống của {machine?.platform === "macos" ? "Mac" : machine?.platform === "windows" ? "Windows" : "thiết bị"}, sau đó băm một chiều trước khi gửi cho Admin. Không gửi serial/UUID gốc.</p><button className="button-quiet" onClick={() => machine && void getRuntime().copyText(machine.machineId)}><Icon name="check" size={15} /> Copy mã máy</button>{machine?.machineIdSource === "installation" && <p className="form-help"><Icon name="key" size={14} /> Hệ điều hành không cung cấp định danh phần cứng; app đã tạo mã cài đặt ổn định cho máy này.</p>}{machine?.machineIdSource === "browser-demo" && <p className="form-error">Đây là mã demo trên trình duyệt. Hãy mở bản cài Electron để lấy mã máy thật.</p>}<div className="device-meta"><span><small>Nền tảng</small><strong>{machine?.platform === "macos" ? "macOS" : machine?.platform === "windows" ? "Windows" : "Linux"}</strong></span><span><small>Kiến trúc</small><strong>{machine?.arch ?? "--"}</strong></span><span><small>App version</small><strong>{machine?.appVersion ?? "--"}</strong></span></div></section><form className="panel-card activation-form" onSubmit={(event) => void activate(event)}><p className="eyebrow">ACTIVATE LICENSE</p><h3>Nhập key của bạn</h3><label className="field-label">License key<input value={key} onChange={(event) => setKey(event.target.value)} placeholder="JACS-XXXX-XXXX-XXXX" autoCapitalize="characters" required /></label><p className="form-help"><Icon name="key" size={14} /> Key sẽ được kiểm tra với API quản lý license và bind với mã máy hiện tại.</p><button type="submit" disabled={!machine || machine.machineIdSource === "browser-demo" || !key.trim()}><Icon name="arrow" size={16} /> Kích hoạt tool</button>{saved && <button type="button" className="button-danger outline-danger" onClick={() => void clear()}>Gỡ license khỏi thiết bị</button>}{message && <p className={message.includes("thành công") ? "form-success" : "form-error"}>{message}</p>}</form></div><p className="activation-endpoint"><span>API environment</span><code>{getApiBaseUrl()}</code></p></div>;
}
